# SPDX-License-Identifier: GPL-2.0-only
#
# Makefile for the UART input drivers
#

obj-$(CONFIG_UART_HID_CORE)			+= uart-hid.o

uart-hid-objs					=  uart-hid-core.o

obj-$(CONFIG_UART_HID_OF)			+= uart-hid-of.o
